# version: '3.8'


services:
    chama-app:
        build: .
        ports:
            - "4000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=production 