name: CI/CD for Chama

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose (if needed)
        run: sudo apt-get update && sudo apt-get install -y docker compose

      - name: Build and run Docker Compose
        run: docker compose up --build -d

      - name: Run tests
        run: docker compose exec -T chama-app npm test

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image to Docker Hub
        run: |
          docker compose build
          docker tag chama-chama-app neemamwende/chama:latest
          docker push neemamwende/chama:latest

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
